// <auto-generated />
namespace HRS.Migrations.HRSDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Admin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Admin));
        
        string IMigrationMetadata.Id
        {
            get { return "201404141447452_Admin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
